In [1]:
import torch 
import numpy as np

In [2]:
data = [[1,2],[2,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [2, 4]])

In [4]:
np_array = np.array(data)

In [5]:
n_np = torch.from_numpy(np_array)

In [6]:
n_np

tensor([[1, 2],
        [2, 4]])

In [7]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [8]:
import torch

In [9]:
import torch.nn as nn

In [10]:
import torchvision
import torchvision.transforms as transforms

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [12]:
device

device(type='cpu')

In [13]:
input_size = 784
hidden_size = 500
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

In [14]:
class NeuralNet(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet,self).__init__()
        self.fc1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.fac2 = nn.Linear(hidden_size,num_classes)
    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [15]:
model = NeuralNet(input_size,hidden_size,num_classes).to(device)

In [16]:
# MNIST dataset 
train_dataset = torchvision.datasets.MNIST(root='../../data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),  
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data', 
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)

# Fully connected neural network with one hidden layer
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [17]:
model = NeuralNet(input_size, hidden_size, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)  

In [18]:
total_step = len(train_loader)

In [19]:
total_step

600

In [20]:
for epoch in range(num_epochs):
    for i, (images,labels) in enumerate(train_loader):
        images = images.reshape(-1,28*28).to(device)
        labels = labels.to(device)

        outputs = model(images)
        loss = criterion(outputs,labels)


        optimizer.zero_grad()

        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print('Epoch [{}/{}] Step [{}/{}], Loss {:.4f}'.format(epoch+1, num_epochs, i + 1, total_step, loss.item()))

    

Epoch [1/5] Step [100/600], Loss 0.4295
Epoch [1/5] Step [200/600], Loss 0.3002
Epoch [1/5] Step [300/600], Loss 0.1335
Epoch [1/5] Step [400/600], Loss 0.1103
Epoch [1/5] Step [500/600], Loss 0.1615
Epoch [1/5] Step [600/600], Loss 0.1810
Epoch [2/5] Step [100/600], Loss 0.1458
Epoch [2/5] Step [200/600], Loss 0.1545
Epoch [2/5] Step [300/600], Loss 0.0635
Epoch [2/5] Step [400/600], Loss 0.0523
Epoch [2/5] Step [500/600], Loss 0.1774
Epoch [2/5] Step [600/600], Loss 0.2839
Epoch [3/5] Step [100/600], Loss 0.1411
Epoch [3/5] Step [200/600], Loss 0.0323
Epoch [3/5] Step [300/600], Loss 0.0390
Epoch [3/5] Step [400/600], Loss 0.0721
Epoch [3/5] Step [500/600], Loss 0.0396
Epoch [3/5] Step [600/600], Loss 0.1184
Epoch [4/5] Step [100/600], Loss 0.0248
Epoch [4/5] Step [200/600], Loss 0.0692
Epoch [4/5] Step [300/600], Loss 0.0879
Epoch [4/5] Step [400/600], Loss 0.0290
Epoch [4/5] Step [500/600], Loss 0.0614
Epoch [4/5] Step [600/600], Loss 0.0720
Epoch [5/5] Step [100/600], Loss 0.0581


In [21]:
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data,1)
        total+=labels.size(0)
        correct += (predicted == labels).sum().item()

    print("Accuracy of the network on the 100090 test images {} %".format(100 * correct/total))

Accuracy of the network on the 100090 test images 97.84 %


In [22]:
torch.save(model.state_dict(),'model.ckpt')