In [1]:
print("Hello, World!")

Hello, World!


In [4]:
class Car:

    pass

audi = Car()
bmw = Car()

In [5]:
print(audi)

In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
import torch
print(torch.__version__)


2.5.1


In [6]:
import torch 
import numpy as np

In [7]:
data = [[1,2],[2,4]]
x_data = torch.tensor(data)

In [8]:
x_data

tensor([[1, 2],
        [2, 4]])

In [9]:
np_array = np.array(data)

In [10]:
n_np = torch.from_numpy(np_array)

In [11]:
n_np

tensor([[1, 2],
        [2, 4]])

In [12]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [13]:
import torch

In [ ]:
import torch.nn as nn

In [15]:
import torchvision
import torchvision.transforms as transforms

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [17]:
device

device(type='cpu')

In [18]:
input_size = 784
hidden_size = 500
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

In [30]:
class NeuralNet(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet,self).__init__()
        self.fc1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.fac2 = nn.Linear(hidden_size,num_classes)
    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [31]:
model = NeuralNet(input_size,hidden_size,num_classes).to(device)

In [36]:
# MNIST dataset 
train_dataset = torchvision.datasets.MNIST(root='../../data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),  
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data', 
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)

# Fully connected neural network with one hidden layer
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [39]:
model = NeuralNet(input_size, hidden_size, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)  

ModuleNotFoundError: No module named 'torch._dynamo'